export const ADD_PROJECT = 'ADD_PROJECT';
export const COURSES_LOADING = 'COURSES_LOADING';
export const COURSES_FAILED = 'COURSES_FAILED';
export const ADD_COURSES = 'ADD_COURSES';
export const ADD_PROJECTS = 'ADD_PROJECTS';
export const PROJECTS_FAILED = 'PROJECTS_FAILED';